### ISSUE TITLE
Make it possible to use IP subnets for filter rules

### ISSUE THREAD

**Issue by hardfalcon** [SilentOrbit/negotiator#13]
Some video streaming sites (for example xhamster or cam4) don't use DNS host names, but plain IP adresses for their content servers. This has the annoying side effect that you have to add a new rule for every single video you see, or you have to add a wildcard rule allowing connections to _any_ server, as wildcards can only be used for subdomains (eg only on the "beginning" of a hostname, but not on the "end" like it would be needed for IP subnets.

As wildcards wouldn't be a proper solution for plain IP addresses anyhow, I suggest to support the CIDR notation for IP subnets. Users could simply look u what IP block a certain IP address belongs to using a simple WHOIS query and then whitelist (or blacklist) the whole IP block.

**Comment by hultqvist** [comment]
Closing this as manifest V3 doesn't support this type of condition.
